### ISSUE TITLE
Hide Console?

### ISSUE THREAD

**Issue by bc-185** [pfmoore/shimmy#2]
Is there any way to hide the console? I've been trying to make the console not appear because the app I'm using only has a GUI.

**Comment by pfmoore** [comment]
You'd need to recompile the stub as a GUI-mode executable, and use the `--stub` option to point to your modified stub.

You should also do something about the error handling, as writing to stderr isn't valid in a GUI program.

**Comment by bc-185** [comment]
For the app that I'm using, after it is launched, the console doesn't close. Are there any options to make the executable close?

**Comment by pfmoore** [comment]
I already explained, not without modifying (and rebuilding) the stub.

**Comment by bc-185** [comment]
This solution from #1 was the right one for me.
`python subsystem.py <consoleapp> <guiappname> gui`
