### ISSUE TITLE
Feature request, embed icon

### ISSUE THREAD

**Issue by b8e5n** [pfmoore/shimmy#4]
Great work, creating an exe file out of cmd is super easy.
However, one of the reasons I wanted an exe file is to have a icon specific to the program. I find some alternatives to change within the executable, but I'd rather embed it directly.
I know I can create a shortcut and then change the icon, but then building an exe file would not be needed as I can already do that with shortcut of cmd.exe.
Sorry but I cannot help with that as this is really not within my competences.

**Comment by pfmoore** [comment]
I (briefly) looked into this in the past. It's not straightforward to achieve, and would add a lot of complexity to what's meant to be a relatively simple utility.

I believe there are applications that let you change the icon (and other resources) for any executable, so I suggest you locate one of those and use it to set your own icon on the generated executable.

**Comment by stonebig** [comment]
It seems someone nailed the solution a long time ago: https://gist.github.com/flyx/2965682
If:
- I rewrite the "print" in a Python 3 way
- I apply the recipe on a just generated shimmy executable
- I get apparently the graal-long-searchtime dreamed result


```
https://gist.github.com/flyx/2965682
# only change: rewrite the"print" in Python 3  style
import win32api, win32con
import os, os.path
import struct
import math

def checkPath(path, mode):
    if not os.path.exists(path) or not os.path.isfile(path):
        raise ValueError("{0} does not exist or isn't a file.".format(path))
    if not os.access(path, mode):
        raise ValueError("Insufficient permissions: {0}".format(path))

def updateExecutableIcon(executablePath, iconPath):
    """
    Updates the icon of a Windows executable file.
    """
    
    checkPath(executablePath, os.W_OK)
    checkPath(iconPath, os.R_OK)
    
    handle = win32api.BeginUpdateResource(executablePath, False)
    
    icon = open(iconPath, "rb")
    
    fileheader = icon.read(6)
    
    # Read icon data
    image_type, image_count = struct.unpack("xxHH", fileheader)
    print ("Icon file has type {0} and contains {1} images.".format(image_type, image_count))
    
    icon_group_desc = struct.pack("<HHH", 0, image_type, image_count)
    icon_sizes = []
    icon_offsets = []
    
    # Read data of all included icons
    for i in range(1, image_count + 1):
        imageheader = icon.read(16)
        width, height, colors, panes, bits_per_pixel, image_size, offset =\
            struct.unpack("BBBxHHLL", imageheader)
        print ("Image is {0}x{1}, has {2} colors in the palette, {3} planes, {4} bits per pixel.".format(
            width, height, colors, panes, bits_per_pixel));
        print ("Image size is {0}, the image content has an offset of {1}".format(image_size, offset));
        
        icon_group_desc = icon_group_desc + struct.pack("<BBBBHHIH",
            width,          # Icon width
            height,         # Icon height
            colors,         # Colors (0 for 256 colors)
            0,              # Reserved2 (must be 0)
            panes,          # Color planes
            bits_per_pixel, # Bits per pixel
            image_size,     # ImageSize
            i               # Resource ID
        )
        icon_sizes.append(image_size)
        icon_offsets.append(offset)
    
    # Read icon content and write it to executable file
    for i in range(1, image_count + 1):
        icon_content = icon.read(icon_sizes[i - 1])
        print ("Read {0} bytes for image #{1}".format(len(icon_content), i))
        win32api.UpdateResource(handle, win32con.RT_ICON, i, icon_content)
        
    win32api.UpdateResource(handle, win32con.RT_GROUP_ICON, "MAINICON", icon_group_desc)
    
    win32api.EndUpdateResource(handle, False)
    
# Use some files I found lying around
updateExecutableIcon("example.exe", "test.ico")
```

**Comment by stonebig** [comment]
our hero who nailed it, apparently 12 years ago
![image](https://github.com/user-attachments/assets/0d025765-6038-4a5a-8c97-a940f9fa0699)

**Comment by pfmoore** [comment]
Cool - but is that not just what I talked about above, "an application that lets you set the icon on any executable"?

Having a pywin32 dependency, and needing to maintain those opaque structure definitions, is what I consider adding a lot of complexity. So I (still) don't intend to add this to the code here, but I'm glad there's a Python solution for those who want it.
