### ISSUE TITLE
the 100 characters limit

### ISSUE THREAD

**Issue by stonebig** [pfmoore/shimmy#6]
is the 100 character limit arbitrary ?
If not, how to get to 200 ?

Do we just need to replace "100" per "200" in https://github.com/pfmoore/shimmy/blob/master/mkshim.py ?

**Comment by pfmoore** [comment]
It's arbitrary in that there was no particular reason I chose it, but it is hard coded. If you want to change it, you need to change the stub and rebuild `mkshim.py`.

To be honest, I don't even remember how to rebuild `mkshim.py` - briefly checking `stub.c`, it seems to have a different marker, suggesting that there's either a step I did that I've since forgotten, or the stub source is out of date with `mkshim.py`.

**Comment by stonebig** [comment]
So, looking on the super-simple code of 2014-08-04 end-of-day, time of the 'glorious' mkshim.py the supposed limit at the time was 1024 characters. So I'll get adventurous on myself to see if 200 characters can bite me.

![image](https://github.com/user-attachments/assets/03821908-7746-4ecb-913c-1bce43a537a1)

**Comment by stonebig** [comment]
maybe didn't look at the right place... 
![image](https://github.com/user-attachments/assets/84d5dfaf-3c2d-42ee-b50c-3f6bf0c9862e)

**Comment by pfmoore** [comment]
`mkshim.py` assumes the version of `stub.c` that's in https://github.com/pfmoore/shimmy/commit/7bcbf56fbc207a0208035b610a69e16e81861c2c

See the section "Current WIP changes (undocumented)" for how the current code works (in particular, you don't need `mkshim.py`, you just compile `stub.c` and prepend it to your executable).

**Comment by pfmoore** [comment]
> So I'll get adventurous on myself to see if 200 characters can bite me.

You'll probably get bitten by https://github.com/pfmoore/shimmy/blob/master/mkshim.py#L27 which assumes that the embedded stub executable contains the marker string (100 "X"s).

Honestly, you'd probably be better simply modifying the `stub.c` code to hardcode the command you want to run, and compiling a custom shim that way.

**Comment by stonebig** [comment]
Yes, so:
- I did went back to Initial commit of 2014-01-26
- stub.c:
  - copy stub.c to stub200.c, doubling "static wchar_t MARKER[] to "X"*200
  -  then from VisualStudio build tool prompt:
  `cl stub200.c`
  - .... generating a big nice stub200.exe 
- template.py
   - in a modified template200.py, use max_limit=200 instead of repeating 100
   - re-apply 2014-08-04 use of 'shim' / 'mkshim' wording
- build.py
   - in a modified build 200.py, use max_limit=200 instead of repeating 100
   - use f'template{max_limit].py'
   - generate f'mkshim{max_limit}.py'
- and then from the command line
    `python build200.py`

and then, apparently, this works:
`python mkshim200.py -f my_IDLE_python201.exe -c "./python-3.13.0rc1.amd64/python.exe                                                                     ./python-3.13.0rc1.amd64/Lib/idlelib/idle.pyw"`

**Comment by stonebig** [comment]
the new launchers are still a bit bigger, even if I do the exercise for 100. I presume modern Visual Studio includes more stuff.

don't know how to make it back in you original size of 54k, now stuck at 107K

**Comment by pfmoore** [comment]
I really don't recall. Maybe I was just using an older version of MSVC, which had a leaner C runtime? The executable wrappers pip produces are about 108k, scoop produces shims that are 120k or so, the `py.exe` launcher is 766k. So I don't think anyone really cares in practice about squeezing the last byte out of a wrapper executable on Windows these days...

**Comment by stonebig** [comment]
my work is in https://github.com/stonebig/shimmy/tree/shimmy240
